### ISSUE TITLE
CI failure due to external site issue

### ISSUE THREAD

**Issue by rashmihunt** [strongloop/loopback-connector-soap#61]
Work
- Modify the test case to handle if the external WSDL location is unavailable  http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL  

- Add new example stockquote service to strong-soap

- Update  strong-soap blog changing the code snippets and text to use stoquote web service instead of weather web service and send it to Dave Whitely.

CI log
 https://cis-jenkins.swg-devops.com/job/ds/job/loopback-connector-soap~3.x/51/consoleFull#-207526304206f8fc75-e0b9-479e-b471-e8fe633361ff

**Comment by eddiemonge** [comment]
We should be setting up a local proxy/mock for this instead of hitting an actual site. That way its not dependent on the external site or the network working correctly and perfectly every time.

One example implementation is to spin up a mock server in the before task and tear it down in the after. The mock server would grab all requests to the "external server" address and return a correct response (based on what the test is asking for: success, failed, timed out).

**Comment by rashmihunt** [comment]
@eddiemonge We have many many tests in strong-soap module which exactly does what you mentioned above. The web service, server side implementation, we have in strong-soap is mock/testing purpose only. It's good to have tests like the tests in this repository which invokes external webservice like weather web service which is what most customer scenarios are.  As discussed during sprint the 3 tests are skipped for now until we find another reliable external web service at which point we will have to change the test case in this module, loopback connector documentation, strong-soap readme, samples which all currently refer to weather web service which is broken.

**Comment by eddiemonge** [comment]
I still think it should not be doing an actual http call for the service and instead use a local server to mock the call. It can deliver the same response (header/body) the external service uses but in a reliable way. If you want the unreliability it can easily be setup for that as well.

Not making an actual call will make the tests faster as well.

**Comment by eddiemonge** [comment]
Ok I think my point is getting lost in terminology. I shouldn't say mock the call. What I mean is, instead of relying on an external service, create our own simple service that can run locally in the project and make calls to that. Then we can that to the documentation or whatever else and when people check out this repo they have reliable access to that service.

We can make this service as simple or as complicated as the tests/our needs dictate and we would have full control over it. Relying on external services means we are reliant on them and have no control over any changes they make to their service, or their availability. Creating our own service should be trivial and not time consuming I think.

@rashmihunt @raymondfeng what do you think about that approach.
