### ISSUE TITLE
SOAP connector - correct examples, etc, in README

### ISSUE THREAD

**Issue by CoreSoft2** [strongloop/loopback-connector-soap#74]
README is there for a good reason. Mammoths like IBM and MS fell behind & now piggy backing on open source to pollute the waters.

Has anyone successfully ran examples?

Is it worth digging into it or just use node to write custom connector?

**Comment by superkhau** [comment]
@CoreSoft2 What is the exact issue? Are the README instructions wrong or do the examples not work or both?

**Comment by CoreSoft2** [comment]
Hi, None of the examples work. They pointing to code that doesn't exists, even going to site and setting it up, sill no luck. Mind you, everyone who what to try, will not spend too much time digging into it!

**Comment by rashmihunt** [comment]
@ritch @crandmck @superkhau  The history of this README dates back before my time. It's important to fix this README with correct URLs and code sample snippets, can we prioritize this to upcoming sprint? @crandmck  will you be able to pull this into next sprint and fix it? Or @mpatsute can fix in the next sprint?

**Comment by crandmck** [comment]
Refer to https://github.com/strongloop/strong-soap for example WSDL that currently works.

There were also some formatting issues with the table.  I fixed those in [fix-readme](https://github.com/strongloop/loopback-connector-soap/blob/fix-readme/README.md) branch.  Please use that branch for additional changes.

**Comment by rashmihunt** [comment]
@crandmck Work item for fixing the sample for this connector https://github.com/strongloop-internal/scrum-asteroid/issues/179

**Comment by rashmihunt** [comment]
@crandmck Fixed soap examples in loopback-exmaple-connector - https://github.com/strongloop-community/loopback-example-connector/tree/soap

Added periodictable-rest.js to showcase how to use loopback-connector-soap and use loopback APIs to create REST APIs. Please base your README code snippet changes in loopback-connector-soap based on this example
Added periodictable-ws.js to showcase just loopback-connector-soap usage
Updated Readme.md to reflect above changes.
Deleted weather-rest.js and weather-ws.js since they don't work. Hence above working samples are added.
Updated packages.json to be up to date

**Comment by crandmck** [comment]
Updated the README to use working example SOAP service and fixed various other issues.
